name: 'Packages Split'

on:
    push:
        branches:
            - main
        tags:
            - '*'
jobs:
    packages_split:
        runs-on: ubuntu-latest
        environment: develop
        strategy:
            fail-fast: false
            matrix:
                package: 
                    -
                        local_path: 'monorepo-child-test'
                        split_repository: 'monorepo-child-test'
        steps:
            - uses: actions/checkout@v3
            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                name: Monorepo Split
                uses: "symplify/monorepo-split-github-action@v2.3.0"
                env:
                    GITHUB_TOKEN: ${{ secrets.TOKEN }}
                with:
                    package_directory: 'plugins/${{ matrix.package.local_path }}'
                    repository_organization: 'ryuring'
                    repository_name: '${{ matrix.package.split_repository }}'
                    branch: "main"
                    user_name: "ryuring"
                    user_email: "ryuring55@gmail.com"
            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                name: Monorepo Tagged Split
                uses: "symplify/monorepo-split-github-action@v2.3.0"
                env:
                    GITHUB_TOKEN: ${{ secrets.TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}
                    package_directory: 'plugins/${{ matrix.package.local_path }}'
                    repository_organization: 'ryuring'
                    repository_name: '${{ matrix.package.split_repository }}'
                    branch: "dev"
                    user_name: "ryuring"
                    user_email: "ryuring55@gmail.com"
